config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users
  resources :users
  resources :schedules, only: [:new, :show, :index, :create, :destroy]
  resources :teams, only: [:index, :show]
  resources :requests, only: [:new, :create, :edit, :update]
  patch 'approve', to: 'requests#approve', as: 'approve'
  patch 'done', to: 'requests#done' , as: 'done'
  get 'timeslots', to: 'users#timeslots', as: 'timeslots'
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :user_events
  # has_and_belongs_to_many :users
  has_many :user_events
  has_many :users, through: :user_events
  has_many :requests
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :requestable, polymorphic: true
  belongs_to :event
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  serialize :assignment
  has_many :schedule_timeslots
  has_many :schedule_users
  has_many :timeslots, through: :schedule_timeslots
  has_many :users, through: :schedule_users
end

app/models/schedule_timeslot.rb
class ScheduleTimeslot < ActiveRecord::Base
  belongs_to :schedule
  belongs_to :timeslot
end

app/models/schedule_user.rb
class ScheduleUser < ActiveRecord::Base
  belongs_to :schedule
  belongs_to :user
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :users
  has_many :requests, as: :requestable
end

app/models/timeslot.rb
class Timeslot < ActiveRecord::Base
  has_many :user_timeslots
  has_many :users, through: :user_timeslots
  has_many :schedule_timeslots
  has_many :schedules, through: :schedule_timeslots
  # has_and_belongs_to_many :users
  # has_many :users, :as => :tablers
  def to_label
    "#{time}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :team
  # has_and_belongs_to_many :events
  has_many :user_events
  has_many :events, through: :user_events
  has_many :user_timeslots
  has_many :timeslots, through: :user_timeslots
  # has_and_belongs_to_many :timeslots
  has_many :requests, as: :requestable
  has_many :schedule_users
  has_many :schedules, through: :schedule_users
  def to_label
    "#{first_name} #{last_name}"
  end
end

app/models/user_event.rb
class UserEvent < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/user_timeslot.rb
class UserTimeslot < ActiveRecord::Base
  belongs_to :user
  belongs_to :timeslot
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def show
    @request = Request.find(params[:id])
  end

  def new
    @request = Request.new
    @user = User.find(params[:requestable_id])

  end

  def approve
    @request = Request.find(params[:id])
    @request.approved = true
    @request.done = false
    @request.save
    redirect_to user_path(@request.requestable_id)
  end

  def done
    @request = Request.find(params[:id])
    @request.done = true
    @request.save
    redirect_to user_path(@request.requestable_id)
  end

  def create
    @request = Request.new request_params
    @request.requestor_id = current_user.id
    @request.requestable_type = "User"
    @request.approved = false
    @request.done = false
    # find the user of the page
    # @user = User.find()
    # @request.user =

    @request.save
    redirect_to user_path(@request.requestable_id)
  end

  def edit
    @request = Request.find(params[:id])
  end

  def update
    @request = Request.find(params[:id])
    @request.update(request_params)
    redirect_to user_path(@request.requestable_id)
  end

  private

  def request_params
    params.require(:request).permit(:description, :due_date, :requestable_id)
  end


end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

    def index
        @schedules = Schedule.all
    end


    def new
        @schedule = Schedule.new
        # assignShifts()
    end

    def destroy
        @schedule = Schedule.find(params[:id])
        @schedule.delete
        redirect_to schedules_path
    end

    def create
        @schedule = Schedule.new schedule_params
        def assignShifts
            available_officers = []
            (1..@schedule.shifts).each do |n|
              available_officers.concat(@schedule.users) # concat more if shifts/officer > 1
            end
            if @schedule.timeslots.length * @schedule.numOfOfficers > available_officers.length
                puts "assignShifts sanity check"
                return nil
            end
            assignment = {}
            @schedule.timeslots.each do |f|
                assignment[f] = []
            end
            return recursive_backtracking(assignment, available_officers)
        end

        def valid_assignment(assignment)
            puts assignment
            puts "true?"
            assignment.each do |key, value|
                puts "at all?"
                if value.length != @schedule.numOfOfficers
                    return false
                end
            end
            puts "true right"
            return true
        end

        def recursive_backtracking(assignment, available_officers)
            puts assignment.length
            puts @schedule.timeslots.length
            if valid_assignment(assignment) #not gonna work yet cus each assignment needs to be size 2
                puts "recursive base case"
                return assignment
            end
            puts "before select call"
            temp = select_unassigned_variable(assignment)
            if temp == nil
                return nil
            end
            temp.users.shuffle.each do |f|
                puts "bro"
                if available_officers.include?(f) && !assignment[temp].include?(f)
                  assignment[temp].push(f)
                  available_officers.delete_at(available_officers.index(f) || available_officers.length)
                  new_assignment = recursive_backtracking(assignment, available_officers)
                  if new_assignment != nil
                      return new_assignment
                  end
                  assignment[temp].pop()
                  available_officers.push(f)
                end
            end
            return nil
        end

        def select_unassigned_variable(assignment)
            @schedule.timeslots.each do |f|
                puts "where am i"
                if assignment[f].length < @schedule.shifts# change this to assignment[f].length < shifts/user
                    puts "selecting"
                    return f
                end
            end
            return nil
        end

        @schedule.assignment = assignShifts
        if @schedule.assignment == nil
            @schedule.assignment = {"Error" => []}
        end
        @schedule.save
        redirect_to schedules_path
    end

    private

    def schedule_params
      params.require(:schedule).permit(:title, :shifts, :numOfOfficers, :timeslot_ids => [], :user_ids => []) # description, shifts/officer
    end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
  end
end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def timeslots
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    render "show"
  end

  def user_params
    params.require(:user).permit(:team, :timeslot_ids => [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/requests/edit.html.erb
<h1> Edit your request </h1>
<%= simple_form_for @request do |f| %>
<%= f.input :description %>
<%= f.input :due_date %>
<%= f.submit %>
<% end %>

app/views/requests/new.html.erb
<h1> Make a request </h1>
<%= simple_form_for @request do |f| %>
  <%= f.input :description %>
  Enter the due_date in the format of yyyymmdd
  <%= f.input :due_date %>
  <%= f.hidden_field :requestable_id, value: @user.id %>
  <%= f.submit %>
<% end %>

app/views/schedules/index.html.erb
<h>wats up</h>

<div class="container">
  <div class="row">
    <h3>Schedules</h3>
    <div class="column">

        <tbody>
          <% @schedules.each do |f| %>

              <p>
              <%= f.title %>
              <table class="table">
              <tr>
              <% f.assignment.each do |key, array| %>
                <% if key == "Error"%>
                  <%= "No available schedule" %>
                  <% next %>
                <% end %>
                <td><%= key.time %></td>
                <td><% array.each do |g| %>
                  <%= g.first_name %>
                <% end %></td>
              <% end %>
              </tr>
              </table>
              <p><%= link_to 'remove schedule', schedule_path(:id => f.id), method: :delete %> </p>
            </p>

          <% end %>
        </tbody>

    </div>
  </div>
</div>

<p><%= link_to 'Tabling schedule', new_schedule_path %> </p>

app/views/schedules/new.html.erb
<center><h1> Make a new schedule </h1></center>
<%= simple_form_for @schedule do |f| %>
  <%= f.input :title %>
  <%= f.input :shifts %>
  <%= f.input :numOfOfficers %>
  <%= f.association :timeslots, :as => :check_boxes %>
  <%= f.association :users, :as => :check_boxes %>
  <%= f.submit "Edit schedule", :class => "button_custom" %>
<% end %>

app/views/users/_user.html.erb
<td><%= link_to user.first_name + " " + user.last_name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Officers</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h3>Officer</h3>
<p>Name: <%= @user.first_name + " " + @user.last_name if @user.first_name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<p>Team: <%= link_to @user.team.name, @user.team %> </p>

<h2>Available Tabling time slots</h2>
  <% if @user.timeslots %>
    <% @user.timeslots.each do |timeslot| %>
      <p><%= timeslot.time %></p>
    <% end %>
  <% end %>
<% if @user == current_user %>
  <%= link_to 'Edit available timeslots', timeslots_path(:id => @user.id) %>
<% end %>

<h2>Requests</h2>

  <% if @user.requests %>
    <% @ordered = @user.requests.sort { |a,b| a.due_date <=> b.due_date } %>
    <% @ordered.each do |request| %>
      <p>
        <% if request.approved == false%>
          <%= request.description %>
          due by: <%= request.due_date %>
          <% if request.requestor_id %>
            <% @requestor = User.find(request.requestor_id)%>
            requested by: <%= link_to @requestor.first_name, user_path(@requestor) %>
            <% if request.requestor_id == current_user.id %>
              <%= link_to 'Edit', edit_request_path(request) %>
            <% end %>
            <% if request.requestor_id == current_user.id && request.done == true %>
              <%= button_to "Approve", approve_path(id: request), :class => "button medium", :method => :patch %>
            <% end %>
            <% if request.requestable_id == current_user.id && request.requestable_type == "User" %>
              <% if request.done == false %>
                <%= button_to "Done", done_path(id: request), :class => "button medium", :method => :patch %>
              <% else %>
                <p> done </p>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </p>
    <% end %>
  <% end %>


<p><%= link_to 'make request', new_request_path(:requestable_id => @user.id) %></p>

app/views/users/timeslots.html.erb
<center><h1> Update your available times </h1></center>
<%= simple_form_for @user do |f| %>
  <%= f.association :timeslots, :as => :check_boxes %>
  <%= f.submit "Edit timeslots", :class => "button_custom" %>
<% end %>